CREATE TABLE IF NOT EXISTS NATIONALITY
(
    ID smallint PRIMARY KEY NOT NULL IDENTITY,
    NAME varchar(60) NOT NULL
);

CREATE TABLE IF NOT EXISTS AUTHORS
(
    ID integer PRIMARY KEY NOT NULL IDENTITY,
    FIRSTNAME varchar(50) NOT NULL,
    LASTNAME varchar(50) NOT NULL,
    BIRTHDAY date NOT NULL,
    NATIONALITY smallint NOT NULL,
    CONSTRAINT AUTHORS_NATIONALITY_ID_FK FOREIGN KEY (NATIONALITY) REFERENCES NATIONALITY (ID)
);

CREATE TABLE IF NOT EXISTS BOOKS
(
    ID integer PRIMARY KEY NOT NULL IDENTITY,
    TITLE varchar(100) NOT NULL,
    AUTHOR integer NOT NULL,
    PUBLISHED date NOT NULL,
    STOCK integer NOT NULL,
    CONSTRAINT BOOKS_AUTHORS_ID_FK FOREIGN KEY (AUTHOR) REFERENCES AUTHORS (ID)
);

CREATE TABLE IF NOT EXISTS MEMBERS
(
    ID integer PRIMARY KEY NOT NULL IDENTITY,
    FIRSTNAME varchar(50) NOT NULL,
    LASTNAME varchar(50) NOT NULL
);

CREATE TABLE IF NOT EXISTS BORROWINGS
(
    ID integer PRIMARY KEY NOT NULL IDENTITY,
    BOOK_ID integer NOT NULL,
    MEMBER_ID integer NOT NULL,
    BORROW_DATE date NOT NULL,
    RETURN_DATE date NOT NULL,
    CONSTRAINT BORROWINGS_BOOKS_ID_FK FOREIGN KEY (BOOK_ID) REFERENCES BOOKS (ID),
    CONSTRAINT BORROWINGS_MEMBERS_ID_FK FOREIGN KEY (MEMBER_ID) REFERENCES MEMBERS (ID)
);