INSERT INTO MATCH (ID, ROUND, SCORE, NUMBER_OF_ROUNDS) VALUES (0, "2", 3);
INSERT INTO MATCH (ID, ROUND, SCORE, NUMBER_OF_ROUNDS) VALUES (1, "1", 3);
INSERT INTO MATCH (ID, ROUND, SCORE, NUMBER_OF_ROUNDS) VALUES (2, "1", 3);

INSERT INTO TEAM (ID, NAME, CAPITAN, COACH) VALUES (0, "name_1", "capitan_1", "coach_1");
INSERT INTO TEAM (ID, NAME, CAPITAN, COACH) VALUES (1, "name_2", "capitan_2", "coach_2");
INSERT INTO TEAM (ID, NAME, CAPITAN, COACH) VALUES (2, "name_3", "capitan_3", "coach_3");